export const missionData = {
  brand: {
    title: 'Mission Control',
    subtitle: 'Ross + Sir Alex operating system',
    environment: 'Local-first demo · premium dark UI',
  },
  sections: [
    { id: 'tasks', label: 'Tasks', icon: '◎' },
    { id: 'calendar', label: 'Calendar', icon: '◷' },
    { id: 'projects', label: 'Projects', icon: '▣' },
    { id: 'agents', label: 'Agents', icon: '◉' },
    { id: 'team', label: 'Team', icon: '⌘' },
  ],
  filters: ['All agents', 'All projects', 'This week'],
  headline: {
    title: 'Mission-ready work, minus the tab soup',
    summary:
      'Main view stays on the task board. Calendar, projects, agents, and team structure are one click away without losing the live operational feel.',
    cta: '+ New task',
  },
  overview: [
    { label: 'This week', value: '19', detail: 'Tasks touched across active projects', tone: 'blue' },
    { label: 'In progress', value: '7', detail: 'Workstreams currently moving', tone: 'yellow' },
    { label: 'Open projects', value: '5', detail: 'Real initiatives, not decorative cards', tone: 'green' },
    { label: 'On track', value: '86%', detail: 'Good momentum, a few scruffy edges', tone: 'purple' },
  ],
  boardColumns: [
    {
      id: 'backlog',
      title: 'Backlog',
      count: 6,
      accent: 'blue',
      cards: [
        {
          title: 'Model approval queue for Ross decisions',
          summary: 'Design the decision lane so blocked items surface without turning the whole UI into a guilt machine.',
          project: 'Mission Control',
          owner: 'Scholesy',
          eta: 'Tomorrow',
          priority: 'P1',
          tags: ['UI', 'Product'],
        },
        {
          title: 'Wire Mealie milestone proof points',
          summary: 'Convert the current spec pile into a crisp first-demo checklist with evidence criteria.',
          project: 'Mealie',
          owner: 'Carrick',
          eta: 'Thu',
          priority: 'P1',
          tags: ['Spec', 'Decision'],
        },
        {
          title: 'Document backup drill runbook summary',
          summary: 'Add operator-facing notes so the restore drill looks like a system and not a hopeful ritual.',
          project: 'Backup Readiness',
          owner: 'Keano',
          eta: 'Fri',
          priority: 'P2',
          tags: ['Ops'],
        },
      ],
    },
    {
      id: 'in-progress',
      title: 'In Progress',
      count: 3,
      accent: 'yellow',
      cards: [
        {
          title: 'Rebuild Mission Control around reference layout',
          summary: 'Left rail, KPI strip, premium kanban, and believable activity stream. Less mockup soup, more product.',
          project: 'Mission Control',
          owner: 'Scholesy',
          eta: 'Today',
          priority: 'P1',
          tags: ['Frontend', 'Demo'],
        },
        {
          title: 'Audit current cron jobs into calendar lanes',
          summary: 'Make recurring agent work visible by day, owner, and operational purpose.',
          project: 'Mission Control',
          owner: 'Sir Alex',
          eta: 'Today',
          priority: 'P1',
          tags: ['Ops', 'Calendar'],
        },
        {
          title: 'Map current project ownership to agent cards',
          summary: 'Keep bios, workload, and focus believable so the agent panel actually explains something.',
          project: 'Mission Control',
          owner: 'Sir Alex',
          eta: 'Today',
          priority: 'P2',
          tags: ['Content'],
        },
      ],
    },
    {
      id: 'review',
      title: 'Review',
      count: 2,
      accent: 'red',
      cards: [
        {
          title: 'Home Assistant path needs access sanity check',
          summary: 'Approved visual direction exists, but live config workflow is still too brittle for cheerful optimism.',
          project: 'Home Assistant',
          owner: 'Keano',
          eta: 'Waiting',
          priority: 'Risk',
          tags: ['Blocked'],
        },
        {
          title: 'Confirm Mealie demo slice with Ross',
          summary: 'Implementation can move faster once the first milestone proves exactly what it is supposed to prove.',
          project: 'Mealie',
          owner: 'Sir Alex',
          eta: 'Needs input',
          priority: 'P1',
          tags: ['Ross input'],
        },
      ],
    },
    {
      id: 'done',
      title: 'Done',
      count: 4,
      accent: 'green',
      cards: [
        {
          title: 'Mission Control standalone app established',
          summary: 'Project now lives outside homelab, which is frankly where it belonged in the first place.',
          project: 'Mission Control',
          owner: 'Scholesy',
          eta: 'Completed',
          priority: 'Done',
          tags: ['Architecture'],
        },
        {
          title: 'Kitchen dashboard direction approved',
          summary: 'Hero Meal First concept landed. Taste was present. Miracles happen.',
          project: 'Home Assistant',
          owner: 'Sir Alex',
          eta: 'Completed',
          priority: 'Done',
          tags: ['Design'],
        },
      ],
    },
  ],
  scheduleSummary: [
    { label: 'Scheduled jobs', value: '8', tone: 'blue' },
    { label: 'Audits this week', value: '3', tone: 'purple' },
    { label: 'Needs runbook', value: '1', tone: 'yellow' },
  ],
  calendarDays: [
    {
      day: 'Tue 31',
      focus: 'Active now',
      items: [
        { time: '21:03 UTC', name: 'repo-hygiene-audit', owner: 'Keano', type: 'Audit' },
        { time: '22:15 UTC', name: 'mission-control-build-check', owner: 'Scholesy', type: 'Verification' },
      ],
    },
    {
      day: 'Wed 1',
      focus: 'Morning brief',
      items: [
        { time: '09:15 ET', name: 'morning-priority-brief', owner: 'Sir Alex', type: 'Brief' },
        { time: '16:30 UTC', name: 'agent-load-review', owner: 'Sir Alex', type: 'Ops review' },
      ],
    },
    {
      day: 'Thu 2',
      focus: 'Backup discipline',
      items: [
        { time: '14:00 ET', name: 'restore-drill-checkpoint', owner: 'Keano', type: 'Operational check' },
      ],
    },
    {
      day: 'Fri 3',
      focus: 'Spec alignment',
      items: [
        { time: '16:30 UTC', name: 'spec-drift-review', owner: 'Sir Alex', type: 'Audit' },
        { time: '17:15 UTC', name: 'weekly-demo-polish-pass', owner: 'Scholesy', type: 'Quality pass' },
      ],
    },
  ],
  projects: [
    {
      name: 'Mission Control dashboard',
      status: 'In progress',
      health: 'Shipping',
      owner: 'Scholesy',
      phase: 'Demo polish',
      summary: 'Turn the prototype into a credible operating surface Ross would actually want to keep open.',
      next: 'Connect task lanes and side panels to semi-live workspace data.',
      blockers: 'None right now.',
    },
    {
      name: 'Mealie selective sharing',
      status: 'Review',
      health: 'Decision needed',
      owner: 'Scholesy + Carrick',
      phase: 'Milestone boundary',
      summary: 'Canonical cookbook sharing model is scaffolded; the first demo story still needs a tighter finish line.',
      next: 'Lock what milestone one must prove.',
      blockers: 'Ross decision on demo scope.',
    },
    {
      name: 'Home Assistant dashboard',
      status: 'Done',
      health: 'Shipped',
      owner: 'Ross',
      phase: 'Complete',
      summary: 'Kitchen dashboard finished. Ross completed the final implementation after agent execution stalled.',
      next: 'None — done.',
      blockers: 'None.',
    },
    {
      name: 'Backup readiness',
      status: 'Planned',
      health: 'Healthy setup',
      owner: 'Keano + Sir Alex',
      phase: 'Runbook + evidence',
      summary: 'Recurring restore checks exist conceptually; now they need visible reporting and boring reliability.',
      next: 'Capture proof from the next audit cycle.',
      blockers: 'No active blocker, just needs follow-through.',
    },
    {
      name: 'Pittsburgh Divorce',
      status: 'In progress',
      health: 'Active build',
      owner: 'Sir Alex',
      phase: 'UI design',
      summary: 'Law firm website. Three UI variants to build and compare: authority/trust-first, conversion/urgency-first, guided/clarity-first.',
      next: 'Build and ship the three UI design variants.',
      blockers: 'None.',
    },
  ],
  pressurePoints: [
    {
      type: 'Approval',
      project: 'Mealie selective sharing',
      title: 'Confirm milestone-one proof point',
      detail: 'The backend slice is moving, but the first demo still wants a brutally clear success definition.',
      owner: 'Sir Alex',
      next: 'Lock the MVP checkpoint and stop being vague about it.',
      tone: 'purple',
    },
    {
      type: 'Blocker',
      project: 'Home Assistant dashboard',
      title: 'Live config workflow is still brittle',
      detail: 'Approved direction exists, but the iteration path remains annoying enough to slow down clean execution.',
      owner: 'Keano',
      next: 'Stabilize the edit/verify loop before pretending this is frictionless.',
      tone: 'yellow',
    },
  ],
  agents: [
    {
      name: 'Sir Alex',
      role: 'Front door / orchestrator / executor',
      status: 'Active',
      load: '100%',
      bio: 'Single front door. Owns orchestration, execution, and the Ross relationship directly. No handoff theater. Ships the work.',
      focus: 'Mission Control, Pittsburgh Divorce UIs, project execution',
      traits: ['Calm operator', 'Context keeper', 'Direct executor'],
    },
  ],
  team: {
    org: [
      {
        title: 'Ross',
        subtitle: 'Principal / decision-maker',
        children: ['Sir Alex'],
      },
      {
        title: 'Sir Alex',
        subtitle: 'Front door / orchestrator / executor',
        children: ['Sub-agents (temporary, task-scoped only)'],
      },
    ],
    principles: [
      'Ross gets one coherent front door. Sir Alex is that front door.',
      'No persistent specialist personas. Work gets done directly, not relayed.',
      'Sub-agents are used only for bounded parallel slices, never as the relationship layer.',
    ],
  },
  activity: [
    { actor: 'Scholesy', time: '12m ago', title: 'Shifted dashboard to reference-style layout', detail: 'Left rail, KPI strip, and central kanban now drive the page.' },
    { actor: 'Sir Alex', time: '28m ago', title: 'Scheduled review cadence tightened', detail: 'Cron lane now groups audits, briefs, and operational checks by day.' },
    { actor: 'Sir Alex', time: '41m ago', title: 'Agent cards reframed around useful bios', detail: 'Roles now read like working teammates instead of flavor text mannequins.' },
    { actor: 'Keano', time: '1.9h ago', title: 'Flagged Home Assistant access risk', detail: 'Live config path still too brittle for happy-path pretending.' },
    { actor: 'Carrick', time: '2.4h ago', title: 'Mealie milestone questions surfaced', detail: 'Spec scaffolding exists, but demo proof points want an explicit call.' },
    { actor: 'System', time: 'Today', title: 'Repo hygiene remains mostly healthy', detail: 'No fire, just a few classic “future-us will remember” landmines.' },
  ],
  insights: [
    { label: 'Need Ross input', value: '2', note: 'Mostly Mealie milestone and HA sequencing', tone: 'yellow' },
    { label: 'Blocked work', value: '1', note: 'Home Assistant access remains the sore spot', tone: 'red' },
    { label: 'Best momentum', value: 'Mission Control', note: 'Fastest-moving and most demo-ready stream', tone: 'green' },
  ],
  statsNote: {
    title: 'Stats',
    summary: 'Planned Mission Control section for agent scorecards, skill usage, criticality, missed assists, and trend lines over time.',
    focus: [
      'Which skills each agent uses most',
      'How often skills are used',
      'Criticality / leverage score by skill',
      'Missed-assist moments where the right skill was not used',
      'Agent trend lines over time'
    ]
  }
};
