export const missionData = {
  brand: {
    title: 'Mission Control',
    subtitle: 'Ross + Sir Alex operating system',
    environment: 'Local-first demo · premium dark UI',
  },
  sections: [
    { id: 'tasks', label: 'Tasks', icon: '◎' },
    { id: 'calendar', label: 'Calendar', icon: '◷' },
    { id: 'projects', label: 'Projects', icon: '▣' },
    { id: 'agents', label: 'Agents', icon: '◉' },
    { id: 'team', label: 'Team', icon: '⌘' },
  ],
  filters: ['All agents', 'All projects', 'This week'],
  headline: {
    title: 'Mission-ready work, minus the tab soup',
    summary:
      'Main view stays on the task board. Calendar, projects, agents, and team structure are one click away without losing the live operational feel.',
    cta: '+ New task',
  },
  overview: [
    { label: 'This week', value: '19', detail: 'Tasks touched across active projects', tone: 'blue' },
    { label: 'In progress', value: '7', detail: 'Workstreams currently moving', tone: 'yellow' },
    { label: 'Open projects', value: '5', detail: 'Real initiatives, not decorative cards', tone: 'green' },
    { label: 'On track', value: '86%', detail: 'Good momentum, a few scruffy edges', tone: 'purple' },
  ],
  boardColumns: [
    {
      id: 'backlog',
      title: 'Backlog',
      count: 6,
      accent: 'blue',
      cards: [
        {
          title: 'Model approval queue for Ross decisions',
          summary: 'Design the decision lane so blocked items surface without turning the whole UI into a guilt machine.',
          project: 'Mission Control',
          owner: 'Builder',
          eta: 'Tomorrow',
          priority: 'P1',
          tags: ['UI', 'Product'],
        },
        {
          title: 'Wire Mealie milestone proof points',
          summary: 'Convert the current spec pile into a crisp first-demo checklist with evidence criteria.',
          project: 'Mealie',
          owner: 'Researcher',
          eta: 'Thu',
          priority: 'P1',
          tags: ['Spec', 'Decision'],
        },
        {
          title: 'Document backup drill runbook summary',
          summary: 'Add operator-facing notes so the restore drill looks like a system and not a hopeful ritual.',
          project: 'Backup Readiness',
          owner: 'Infra-operator',
          eta: 'Fri',
          priority: 'P2',
          tags: ['Ops'],
        },
      ],
    },
    {
      id: 'in-progress',
      title: 'In Progress',
      count: 3,
      accent: 'yellow',
      cards: [
        {
          title: 'Rebuild Mission Control around reference layout',
          summary: 'Left rail, KPI strip, premium kanban, and believable activity stream. Less mockup soup, more product.',
          project: 'Mission Control',
          owner: 'Builder',
          eta: 'Today',
          priority: 'P1',
          tags: ['Frontend', 'Demo'],
        },
        {
          title: 'Audit current cron jobs into calendar lanes',
          summary: 'Make recurring agent work visible by day, owner, and operational purpose.',
          project: 'Mission Control',
          owner: 'Bruno',
          eta: 'Today',
          priority: 'P1',
          tags: ['Ops', 'Calendar'],
        },
        {
          title: 'Map current project ownership to agent cards',
          summary: 'Keep bios, workload, and focus believable so the agent panel actually explains something.',
          project: 'Mission Control',
          owner: 'Sir Alex',
          eta: 'Today',
          priority: 'P2',
          tags: ['Content'],
        },
      ],
    },
    {
      id: 'review',
      title: 'Review',
      count: 2,
      accent: 'red',
      cards: [
        {
          title: 'Home Assistant path needs access sanity check',
          summary: 'Approved visual direction exists, but live config workflow is still too brittle for cheerful optimism.',
          project: 'Home Assistant',
          owner: 'Infra-operator',
          eta: 'Waiting',
          priority: 'Risk',
          tags: ['Blocked'],
        },
        {
          title: 'Confirm Mealie demo slice with Ross',
          summary: 'Implementation can move faster once the first milestone proves exactly what it is supposed to prove.',
          project: 'Mealie',
          owner: 'Sir Alex',
          eta: 'Needs input',
          priority: 'P1',
          tags: ['Ross input'],
        },
      ],
    },
    {
      id: 'done',
      title: 'Done',
      count: 4,
      accent: 'green',
      cards: [
        {
          title: 'Mission Control standalone app established',
          summary: 'Project now lives outside homelab, which is frankly where it belonged in the first place.',
          project: 'Mission Control',
          owner: 'Builder',
          eta: 'Completed',
          priority: 'Done',
          tags: ['Architecture'],
        },
        {
          title: 'Kitchen dashboard direction approved',
          summary: 'Hero Meal First concept landed. Taste was present. Miracles happen.',
          project: 'Home Assistant',
          owner: 'Sir Alex',
          eta: 'Completed',
          priority: 'Done',
          tags: ['Design'],
        },
      ],
    },
  ],
  scheduleSummary: [
    { label: 'Scheduled jobs', value: '8', tone: 'blue' },
    { label: 'Audits this week', value: '3', tone: 'purple' },
    { label: 'Needs runbook', value: '1', tone: 'yellow' },
  ],
  calendarDays: [
    {
      day: 'Tue 31',
      focus: 'Active now',
      items: [
        { time: '21:03 UTC', name: 'repo-hygiene-audit', owner: 'Infra-operator', type: 'Audit' },
        { time: '22:15 UTC', name: 'mission-control-build-check', owner: 'Builder', type: 'Verification' },
      ],
    },
    {
      day: 'Wed 1',
      focus: 'Morning brief',
      items: [
        { time: '09:15 ET', name: 'morning-priority-brief', owner: 'Sir Alex', type: 'Brief' },
        { time: '16:30 UTC', name: 'agent-load-review', owner: 'Bruno', type: 'Ops review' },
      ],
    },
    {
      day: 'Thu 2',
      focus: 'Backup discipline',
      items: [
        { time: '14:00 ET', name: 'restore-drill-checkpoint', owner: 'Infra-operator', type: 'Operational check' },
      ],
    },
    {
      day: 'Fri 3',
      focus: 'Spec alignment',
      items: [
        { time: '16:30 UTC', name: 'spec-drift-review', owner: 'Bruno', type: 'Audit' },
        { time: '17:15 UTC', name: 'weekly-demo-polish-pass', owner: 'Builder', type: 'Quality pass' },
      ],
    },
  ],
  projects: [
    {
      name: 'Mission Control dashboard',
      status: 'In progress',
      health: 'Shipping',
      owner: 'Builder',
      phase: 'Demo polish',
      summary: 'Turn the prototype into a credible operating surface Ross would actually want to keep open.',
      next: 'Connect task lanes and side panels to semi-live workspace data.',
      blockers: 'None right now.',
    },
    {
      name: 'Mealie selective sharing',
      status: 'Review',
      health: 'Decision needed',
      owner: 'Builder + Researcher',
      phase: 'Milestone boundary',
      summary: 'Canonical cookbook sharing model is scaffolded; the first demo story still needs a tighter finish line.',
      next: 'Lock what milestone one must prove.',
      blockers: 'Ross decision on demo scope.',
    },
    {
      name: 'Home Assistant dashboard',
      status: 'Blocked',
      health: 'Access risk',
      owner: 'Infra-operator',
      phase: 'Config stabilization',
      summary: 'Visual direction is approved, but implementation is still constrained by brittle live access.',
      next: 'Stabilize the iteration path.',
      blockers: 'Live config workflow still annoying.',
    },
    {
      name: 'Backup readiness',
      status: 'Planned',
      health: 'Healthy setup',
      owner: 'Infra-operator + Bruno',
      phase: 'Runbook + evidence',
      summary: 'Recurring restore checks exist conceptually; now they need visible reporting and boring reliability.',
      next: 'Capture proof from the next audit cycle.',
      blockers: 'No active blocker, just needs follow-through.',
    },
    {
      name: 'Agent architecture cleanup',
      status: 'Discovery',
      health: 'Worth doing',
      owner: 'Bruno',
      phase: 'Naming + structure review',
      summary: 'Legacy directories and old agent naming still leak confusion into current work.',
      next: 'Plan a cleanup pass that matches the current operating model.',
      blockers: 'Needs sequencing behind active delivery work.',
    },
  ],
  agents: [
    {
      name: 'Sir Alex',
      role: 'Front door / coordinator',
      status: 'Active',
      load: '68%',
      bio: 'Keeps the Ross-facing surface coherent, translates chaos into decisions, and generally prevents dashboard theater from becoming policy.',
      focus: 'Project framing, approvals, summaries',
      traits: ['Calm operator', 'Context keeper', 'Lightly cynical'],
    },
    {
      name: 'Bruno',
      role: 'Supervisor / orchestrator',
      status: 'Busy',
      load: '74%',
      bio: 'Sequences work across agents, spots drift, and tries to keep the whole machine from turning into a to-do list landfill.',
      focus: 'Routing, review queues, operational cadence',
      traits: ['Sequencing brain', 'Dependency wrangler', 'Tolerates ambiguity'],
    },
    {
      name: 'Builder',
      role: 'Implementation',
      status: 'Heads down',
      load: '87%',
      bio: 'Turns vague ambitions into shipped interfaces and working code, occasionally while glaring at reality.',
      focus: 'Mission Control UI, Mealie implementation',
      traits: ['Product-minded', 'Fast shipper', 'Likes clean edges'],
    },
    {
      name: 'Researcher',
      role: 'Research / synthesis',
      status: 'Ready',
      load: '32%',
      bio: 'Finds the sharpest version of the truth, then hands it over without six pages of decorative throat clearing.',
      focus: 'Specs, milestone definition, decision support',
      traits: ['Structured thinker', 'Good at synthesis', 'Low ego'],
    },
    {
      name: 'Infra-operator',
      role: 'Ops / systems / hygiene',
      status: 'Active',
      load: '63%',
      bio: 'Handles the unglamorous but crucial parts: access paths, restore confidence, environment stability, and keeping the lights on.',
      focus: 'Cron jobs, HA access, repo hygiene, backups',
      traits: ['Practical', 'Risk-aware', 'Not impressed by vibes'],
    },
  ],
  team: {
    org: [
      {
        title: 'Ross',
        subtitle: 'Principal / decision-maker',
        children: ['Sir Alex'],
      },
      {
        title: 'Sir Alex',
        subtitle: 'Front door / operating partner',
        children: ['Bruno'],
      },
      {
        title: 'Bruno',
        subtitle: 'Supervisor / orchestration layer',
        children: ['Builder', 'Researcher', 'Infra-operator'],
      },
    ],
    principles: [
      'Ross gets one coherent front door, not a relay race of personas.',
      'Bruno handles sequencing and orchestration behind the curtain.',
      'Specialists own delivery work, not the human relationship.',
    ],
  },
  activity: [
    { actor: 'Builder', time: '12m ago', title: 'Shifted dashboard to reference-style layout', detail: 'Left rail, KPI strip, and central kanban now drive the page.' },
    { actor: 'Bruno', time: '28m ago', title: 'Scheduled review cadence tightened', detail: 'Cron lane now groups audits, briefs, and operational checks by day.' },
    { actor: 'Sir Alex', time: '41m ago', title: 'Agent cards reframed around useful bios', detail: 'Roles now read like working teammates instead of flavor text mannequins.' },
    { actor: 'Infra-operator', time: '1.9h ago', title: 'Flagged Home Assistant access risk', detail: 'Live config path still too brittle for happy-path pretending.' },
    { actor: 'Researcher', time: '2.4h ago', title: 'Mealie milestone questions surfaced', detail: 'Spec scaffolding exists, but demo proof points want an explicit call.' },
    { actor: 'System', time: 'Today', title: 'Repo hygiene remains mostly healthy', detail: 'No fire, just a few classic “future-us will remember” landmines.' },
  ],
  insights: [
    { label: 'Need Ross input', value: '2', note: 'Mostly Mealie milestone and HA sequencing', tone: 'yellow' },
    { label: 'Blocked work', value: '1', note: 'Home Assistant access remains the sore spot', tone: 'red' },
    { label: 'Best momentum', value: 'Mission Control', note: 'Fastest-moving and most demo-ready stream', tone: 'green' },
  ],
};
